# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agent.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='agent.proto',
  package='agent',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0b\x61gent.proto\x12\x05\x61gent\"\'\n\x10OperatingPicture\x12\x13\n\x0bnumMissiles\x18\x01 \x01(\x05\"&\n\x04Plan\x12\x1e\n\x16targetDamageAssessment\x18\x01 \x03(\x05\x32:\n\x05\x41gent\x12\x31\n\x07GetPlan\x12\x17.agent.OperatingPicture\x1a\x0b.agent.Plan\"\x00\x62\x06proto3'
)




_OPERATINGPICTURE = _descriptor.Descriptor(
  name='OperatingPicture',
  full_name='agent.OperatingPicture',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='numMissiles', full_name='agent.OperatingPicture.numMissiles', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=61,
)


_PLAN = _descriptor.Descriptor(
  name='Plan',
  full_name='agent.Plan',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='targetDamageAssessment', full_name='agent.Plan.targetDamageAssessment', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=101,
)

DESCRIPTOR.message_types_by_name['OperatingPicture'] = _OPERATINGPICTURE
DESCRIPTOR.message_types_by_name['Plan'] = _PLAN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OperatingPicture = _reflection.GeneratedProtocolMessageType('OperatingPicture', (_message.Message,), {
  'DESCRIPTOR' : _OPERATINGPICTURE,
  '__module__' : 'agent_pb2'
  # @@protoc_insertion_point(class_scope:agent.OperatingPicture)
  })
_sym_db.RegisterMessage(OperatingPicture)

Plan = _reflection.GeneratedProtocolMessageType('Plan', (_message.Message,), {
  'DESCRIPTOR' : _PLAN,
  '__module__' : 'agent_pb2'
  # @@protoc_insertion_point(class_scope:agent.Plan)
  })
_sym_db.RegisterMessage(Plan)



_AGENT = _descriptor.ServiceDescriptor(
  name='Agent',
  full_name='agent.Agent',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=103,
  serialized_end=161,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetPlan',
    full_name='agent.Agent.GetPlan',
    index=0,
    containing_service=None,
    input_type=_OPERATINGPICTURE,
    output_type=_PLAN,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_AGENT)

DESCRIPTOR.services_by_name['Agent'] = _AGENT

# @@protoc_insertion_point(module_scope)
